"use client";
import {ChevronRight,ImageIcon,Loader2} from "lucide-react";
import type {Character,CinematicImage,Location,SceneCharacterState} from "@/lib/types";

const SHOTS=["extreme close-up","close-up","medium shot","medium wide shot","wide establishing shot","low-angle hero shot","over-the-shoulder shot"] as const;
const ANGLES=["eye level","low angle","high angle","top-down","three-quarter angle","Dutch angle"] as const;
const POSITIONS=["left","center","right","foreground","background"] as const;

export function SceneCard({scene,previous,characters,locations,busy,onPatch,onToggleCharacter,onPatchCharacter,onGenerate}:{
  scene:CinematicImage;previous?:CinematicImage;characters:Character[];locations:Location[];busy:string;
  onPatch:(patch:Partial<CinematicImage>)=>void;onToggleCharacter:(character:Character,enabled:boolean)=>void;onPatchCharacter:(characterId:string,patch:Partial<SceneCharacterState>)=>void;onGenerate:()=>void;
}){
  const selected=new Set(scene.characterStates.map((state)=>state.characterId));
  return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid lg:grid-cols-[330px_1fr]">
    <div className="border-b border-slate-200 bg-slate-50 p-4 lg:border-b-0 lg:border-r">{scene.image?<img src={scene.image} alt={scene.title} className="aspect-video w-full rounded-xl object-cover shadow-sm"/>:<div className="grid aspect-video place-items-center rounded-xl border border-dashed border-slate-300 bg-white text-slate-400"><div className="text-center"><ImageIcon className="mx-auto mb-2"/><div className="text-sm">Scene {scene.sceneNumber}</div></div></div>}<div className="mt-3 flex items-center justify-between"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${scene.status==="completed"?"bg-emerald-100 text-emerald-700":scene.status==="failed"?"bg-red-100 text-red-700":"bg-slate-200 text-slate-600"}`}>{scene.status}</span><button disabled={!!busy} onClick={onGenerate} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{busy===scene.id?<Loader2 className="mr-1 inline animate-spin" size={13}/>:<ChevronRight className="mr-1 inline" size={13}/>} Generate</button></div>{previous&&<div className="mt-3 rounded-xl border border-violet-100 bg-violet-50 p-3 text-xs leading-5 text-violet-800">Scene {previous.sceneNumber} {previous.image?"✓ ready":"⚠ not generated"}. {scene.usePreviousImage?"Previous frame will be sent as continuity reference.":"Previous-frame reference disabled."}</div>}</div>
    <div className="space-y-4 p-4 md:p-5"><div className="grid gap-3 md:grid-cols-[110px_1fr]"><div><div className="text-xs font-bold uppercase tracking-wider text-violet-600">Scene {scene.sceneNumber}</div><div className="mt-1 text-xs text-slate-400">{scene.referenceCount||0} refs last render</div></div><div><input value={scene.title} onChange={(e)=>onPatch({title:e.target.value})} className="w-full rounded-lg border border-slate-200 px-3 py-2 font-bold"/><textarea value={scene.sourceText} onChange={(e)=>onPatch({sourceText:e.target.value})} className="mt-2 min-h-20 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm leading-6"/></div></div>
      <div className="grid gap-2 md:grid-cols-4"><select value={scene.locationId||""} onChange={(e)=>onPatch({locationId:e.target.value||undefined})} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">Continue previous location</option>{locations.map((location)=><option key={location.id} value={location.id}>{location.name}</option>)}</select><select value={scene.cameraShot} onChange={(e)=>onPatch({cameraShot:e.target.value})} className="rounded-lg border border-slate-200 px-3 py-2 text-sm">{SHOTS.map((item)=><option key={item}>{item}</option>)}</select><select value={scene.cameraAngle} onChange={(e)=>onPatch({cameraAngle:e.target.value})} className="rounded-lg border border-slate-200 px-3 py-2 text-sm">{ANGLES.map((item)=><option key={item}>{item}</option>)}</select><input value={scene.cameraDirection} onChange={(e)=>onPatch({cameraDirection:e.target.value})} className="rounded-lg border border-slate-200 px-3 py-2 text-sm" placeholder="Screen direction"/></div>
      <div className="rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="flex flex-wrap items-center gap-3"><div className="text-sm font-bold">Characters present</div>{characters.map((character)=><label key={character.id} className={`flex cursor-pointer items-center gap-2 rounded-full border px-3 py-1.5 text-xs ${selected.has(character.id)?"border-violet-200 bg-violet-50 text-violet-700":"border-slate-200 bg-white text-slate-500"}`}><input type="checkbox" checked={selected.has(character.id)} onChange={(e)=>onToggleCharacter(character,e.target.checked)}/>{character.name}</label>)}</div>
        <div className="mt-3 space-y-3">{scene.characterStates.map((state)=>{const character=characters.find((item)=>item.id===state.characterId);if(!character)return null;return <div key={state.characterId} className="grid gap-2 rounded-xl border border-slate-200 bg-white p-3 md:grid-cols-5"><div><div className="mb-1 text-xs font-bold text-slate-600">{character.name}</div><select value={state.position} onChange={(e)=>onPatchCharacter(character.id,{position:e.target.value})} className="w-full rounded-lg border border-slate-200 px-2 py-2 text-xs">{POSITIONS.map((item)=><option key={item}>{item}</option>)}</select></div><textarea value={state.action} onChange={(e)=>onPatchCharacter(character.id,{action:e.target.value})} className="min-h-16 rounded-lg border border-slate-200 p-2 text-xs" placeholder="Action / movement"/><textarea value={state.direction} onChange={(e)=>onPatchCharacter(character.id,{direction:e.target.value})} className="min-h-16 rounded-lg border border-slate-200 p-2 text-xs" placeholder="Facing / direction"/><textarea value={state.expression} onChange={(e)=>onPatchCharacter(character.id,{expression:e.target.value})} className="min-h-16 rounded-lg border border-slate-200 p-2 text-xs" placeholder="Expression"/><textarea value={state.stateNotes} onChange={(e)=>onPatchCharacter(character.id,{stateNotes:e.target.value})} className="min-h-16 rounded-lg border border-slate-200 p-2 text-xs" placeholder="Injury, weapon, prop, posture"/></div>})}</div>
      </div>
      <div className="grid gap-3 md:grid-cols-[1fr_210px]"><textarea value={scene.continuityNotes} onChange={(e)=>onPatch({continuityNotes:e.target.value})} className="min-h-20 rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm" placeholder="Who entered/exited, injury changes, background damage…"/><div className="rounded-xl border border-slate-200 bg-white p-3"><div className="flex items-center justify-between text-xs font-bold"><span>Continuity</span><span>{scene.continuityStrength}%</span></div><input type="range" min="60" max="100" value={scene.continuityStrength} onChange={(e)=>onPatch({continuityStrength:Number(e.target.value)})} className="mt-2 w-full accent-violet-600"/><label className="mt-3 flex items-center gap-2 text-xs text-slate-600"><input type="checkbox" checked={scene.usePreviousImage} onChange={(e)=>onPatch({usePreviousImage:e.target.checked})}/> Use previous frame</label></div></div>{scene.error&&<div className="rounded-xl bg-red-50 p-3 text-xs text-red-700">{scene.error}</div>}
    </div>
  </div></article>;
}
