"use client";
import type {ChangeEvent} from "react";
import {ImageIcon,MapPinned,Plus,Upload,WandSparkles,Loader2} from "lucide-react";
import type {Character,Location,Project} from "@/lib/types";

export const STYLE_PRESETS=["Cinematic Painting","Epic Fantasy Painting","Dark Fantasy Cinematic","Painterly Realism","Dreamlike Fantasy","Ultra-Detailed Concept Art"] as const;
export const ASPECT_RATIOS=["16:9","9:16","4:5","1:1","21:9"] as const;

export function StoryPanel({project,busy,onPatch,onPlan,onStyleReference}:{
  project:Project;busy:string;onPatch:(patch:Partial<Project>)=>void;onPlan:()=>void;onStyleReference:(event:ChangeEvent<HTMLInputElement>)=>void;
}){
  return <section className="space-y-4"><div className="grid gap-4 lg:grid-cols-[1fr_330px]">
    <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">Full Story</h2><p className="text-sm text-slate-500">AI planner story को visual beats में तोड़ेगा और हर scene में character, movement, direction, location और state track करेगा।</p></div><button disabled={!!busy} onClick={onPlan} className="rounded-xl bg-violet-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{busy==="planning"?<Loader2 className="mr-1 inline animate-spin" size={16}/>:<WandSparkles className="mr-1 inline" size={16}/>} Plan Continuity Scenes</button></div>
      <textarea disabled={!!busy} value={project.story} onChange={(e)=>onPatch({story:e.target.value})} className="min-h-[460px] w-full rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm leading-7 outline-none focus:border-violet-400 focus:bg-white" placeholder="Paste the full story here…"/>
    </article>
    <aside className="space-y-4">
      <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="font-bold">Continuity Mode</div><p className="mt-1 text-xs leading-5 text-slate-500">Strict mode में अगला scene previous frame के बिना generate नहीं होगा।</p><div className="mt-3 grid grid-cols-2 gap-2">{(["strict","balanced"] as const).map((mode)=><button key={mode} onClick={()=>onPatch({continuityMode:mode})} className={`rounded-xl border px-3 py-2 text-sm font-semibold ${project.continuityMode===mode?"border-violet-300 bg-violet-50 text-violet-700":"border-slate-200 bg-white text-slate-600"}`}>{mode}</button>)}</div></article>
      <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="font-bold">World Bible</div><p className="mt-1 text-xs text-slate-500">Permanent world, architecture, era, magic and lighting rules.</p><textarea value={project.worldNotes} onChange={(e)=>onPatch({worldNotes:e.target.value})} className="mt-3 min-h-32 w-full rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm outline-none focus:border-violet-400" placeholder="Example: ruined canyon city; warm sun always from camera-right…"/></article>
      <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="font-bold">Style Reference</div><p className="mt-1 text-xs text-slate-500">वीडियो जैसी overall painting style के लिए master image.</p>{project.styleReferenceImage?<img src={project.styleReferenceImage} alt="Style reference" className="mt-3 h-36 w-full rounded-xl object-cover"/>:<div className="mt-3 grid h-28 place-items-center rounded-xl border border-dashed border-slate-300 bg-slate-50 text-slate-400"><ImageIcon/></div>}<label className="mt-3 flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700"><Upload size={15}/> {project.styleReferenceImage?"Replace":"Upload"} style image<input type="file" accept="image/*" className="hidden" onChange={onStyleReference}/></label></article>
    </aside>
  </div></section>;
}

export function CharactersPanel({characters,busy,onAdd,onUpdate,onUpload}:{characters:Character[];busy:string;onAdd:()=>void;onUpdate:(id:string,patch:Partial<Character>)=>void;onUpload:(id:string,event:ChangeEvent<HTMLInputElement>)=>void}){
  return <section className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-bold">Character Bible</h2><p className="text-sm text-slate-500">Master reference + locked identity facts = हर scene में वही character.</p></div><button disabled={!!busy} onClick={onAdd} className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-bold text-white"><Plus className="mr-1 inline" size={15}/> Add Character</button></div><div className="grid gap-4 md:grid-cols-2">{characters.length?characters.map((character)=><article key={character.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
    <div className="flex gap-4">{character.referenceImage?<img src={character.referenceImage} alt={character.name} className="h-32 w-32 rounded-xl object-cover"/>:<label className="grid h-32 w-32 shrink-0 cursor-pointer place-items-center rounded-xl border border-dashed border-slate-300 bg-slate-50 text-slate-400"><Upload/><input type="file" accept="image/*" className="hidden" onChange={(e)=>onUpload(character.id,e)}/></label>}<div className="min-w-0 flex-1 space-y-2"><input value={character.name} onChange={(e)=>onUpdate(character.id,{name:e.target.value})} className="w-full rounded-lg border border-slate-200 px-3 py-2 font-bold"/><input value={character.role} onChange={(e)=>onUpdate(character.id,{role:e.target.value})} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" placeholder="Role"/><textarea value={character.appearance} onChange={(e)=>onUpdate(character.id,{appearance:e.target.value})} className="min-h-20 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm" placeholder="Face, hair, age look, body, identity"/><input value={character.outfit} onChange={(e)=>onUpdate(character.id,{outfit:e.target.value})} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" placeholder="Canonical outfit / armor"/></div></div>
    <textarea value={character.continuityNotes||""} onChange={(e)=>onUpdate(character.id,{continuityNotes:e.target.value})} className="mt-3 min-h-20 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm" placeholder="Permanent facts: weapon, jewelry, scar side, eye color…"/><div className="mt-3 flex items-center justify-between text-xs text-slate-500"><label className="flex items-center gap-2"><input type="checkbox" checked={character.locked!==false} onChange={(e)=>onUpdate(character.id,{locked:e.target.checked})}/> Lock identity/outfit</label><label className="cursor-pointer font-semibold text-violet-700">Replace reference<input type="file" accept="image/*" className="hidden" onChange={(e)=>onUpload(character.id,e)}/></label></div>
  </article>):<div className="rounded-2xl border border-slate-200 bg-white p-8 text-slate-500">Characters add करें और master reference photos upload करें।</div>}</div></section>;
}

export function LocationsPanel({locations,busy,onAdd,onUpdate,onUpload}:{locations:Location[];busy:string;onAdd:()=>void;onUpdate:(id:string,patch:Partial<Location>)=>void;onUpload:(id:string,event:ChangeEvent<HTMLInputElement>)=>void}){
  return <section className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-bold">Location Bible</h2><p className="text-sm text-slate-500">Same architecture, landmark placement, light direction and atmosphere.</p></div><button disabled={!!busy} onClick={onAdd} className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-bold text-white"><Plus className="mr-1 inline" size={15}/> Add Location</button></div><div className="grid gap-4 md:grid-cols-2">{locations.length?locations.map((location)=><article key={location.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
    <div className="flex gap-4">{location.referenceImage?<img src={location.referenceImage} alt={location.name} className="h-32 w-32 rounded-xl object-cover"/>:<label className="grid h-32 w-32 shrink-0 cursor-pointer place-items-center rounded-xl border border-dashed border-slate-300 bg-slate-50 text-slate-400"><MapPinned/><input type="file" accept="image/*" className="hidden" onChange={(e)=>onUpload(location.id,e)}/></label>}<div className="min-w-0 flex-1 space-y-2"><input value={location.name} onChange={(e)=>onUpdate(location.id,{name:e.target.value})} className="w-full rounded-lg border border-slate-200 px-3 py-2 font-bold"/><textarea value={location.description} onChange={(e)=>onUpdate(location.id,{description:e.target.value})} className="min-h-24 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm" placeholder="Architecture, colors, landmark positions"/><input value={location.lighting} onChange={(e)=>onUpdate(location.id,{lighting:e.target.value})} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" placeholder="Lighting / time / weather"/></div></div><textarea value={location.continuityNotes||""} onChange={(e)=>onUpdate(location.id,{continuityNotes:e.target.value})} className="mt-3 min-h-20 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm" placeholder="Permanent facts: gate left, tower behind, sun from right…"/>
  </article>):<div className="rounded-2xl border border-slate-200 bg-white p-8 text-slate-500">Recurring locations add करें और reference photos रखें।</div>}</div></section>;
}
